### ISSUE TITLE
`\n` inserted on Python 2

### ISSUE THREAD

**Issue by alexander-pecheny** [jfbercher/code_prettify#1]
```
lambda x: x \
 ** x
lambda y: y * y
```

becomes

```
lambda x: x \\n ** x
lambda y: y * y
```

**Comment by jfbercher** [comment]
@peczony 
Ok. It is a bit complicated to pass the string from one language to another and check all characters that have to be escaped/unescaped. 
I feel I corrected that. 
Note that it seems that yapf either 
- don't "convert" intructions with continued lines (checked via `yapf file` on the command line)
- removes the continuation lines (via `FormatCode` with a multiline string) and formats on a single line

I adopted the second strategy here.
