### ISSUE TITLE
'exec_code_verbose' and fork

### ISSUE THREAD

**Issue by EWouters** [jfbercher/code_prettify#2]
Hi Jean-François,

I used your project to create an [extension to convert python2 to 3](https://github.com/EWouters/2to3_cell). 
Are you ok with that?
How should I mention your contribution?

Also in your `code_exec_callback` you use a 'exec_code_verbose' variable. When is it assigned?
```
if (msg.msg_type == "error") {
	if (exec_code_verbose) alert("CODE prettify extension\n Error: " + msg.content.ename + "\n" + msg.content.evalue)
	return
}
```

Thank you for making awesome extensions!

**Comment by jfbercher** [comment]
Hello @EWouters,
Yes of course I agree that you reuse the code (credit in source/Radme is nice). 
Please check (or I will) if the code in my repo is exactly at the same level as in `jupyter_contrib_nbextensions`; I may have commited directly the last modifications at `jupyter_contrib_nbextensions`. 
Making a 2to3 extension is a good idea!! 
[Actually I made a draft but unfinished of something like that for my personal use, so this is very welcome.]
I will review the code, test the extension and suggest possible improvements (I already saw a possible improvement with respect to kernel language use). 
Thanks for this contribution!

**Comment by EWouters** [comment]
After I forked it I actually used the js file in the [jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions/tree/master/src/jupyter_contrib_nbextensions/nbextensions/code_prettify) to copy the functions from.
There were indeed a few changes in the code, but I used the latest ones so that should be ok.

I also edited the readme file and mentioned you there. There was already a link to your repo in the code.

As for the issue I opened up here, when testing the javascript code in a notebook cell the `exec_code_verbose` gave me an error, so I commented out the [if statement](https://github.com/EWouters/2to3_cell/blob/master/2to3_cell.js#L69) containing the `exec_code_verbose`

```
		alert("CODE 2to3 extension\n Error: " + msg.content.ename + "\n" + msg.content.evalue)
	    //if (exec_code_verbose) alert("CODE 2to3 extension\n Error: " + msg.content.ename + "\n" + msg.content.evalue)
```

Although I didn't get errors if I added it back in I am not sure whether to add it back in.

Thank you for reviewing the code!

**Comment by EWouters** [comment]
I found the declaration of the [`exec_code_verbose`](https://github.com/jfbercher/code_prettify/blob/master/code_prettify.js#L16) variable.
Thanks
